function ContactMenu()
    local myVector = CS.MyVector()
    local zaloCommand = CS.Command("Zalo", function()
        CS.GameCanvas.startOKDlg("Zalo: 0986.106.250")
    end)
    myVector:addElement(zaloCommand)
    local fbCommand = CS.Command("Facebook", function()
        CS.UnityEngine.Application.OpenURL("https://www.facebook.com/hairmodnro/")
    end)
    myVector:addElement(fbCommand)
    local ytbCommand = CS.Command("Youtube", function()
        CS.UnityEngine.Application.OpenURL("https://www.youtube.com/@HairMod")
        end
        )
    myVector:addElement(ytbCommand)
    local tiktokCommand = CS.Command("Tiktok", function()
            CS.UnityEngine.Application.OpenURL("https://www.tiktok.com/@haircsharp?_t=ZS-8uFbs2MEhuS&_r=1")
        end)
    local TestCase = CS.Command("HairMod", function()
            CS.GameScr.info1.addInfo("Test Case",0)
        end)
    myVector:addElement(tiktokCommand)
    myVector:addElement(TestCase)
            CS.GameCanvas.menu:startAt(myVector, 0)
end
